// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inet                 string   `protobuf:"bytes,2,opt,name=inet,proto3" json:"inet,omitempty"`
	Net                  string   `protobuf:"bytes,3,opt,name=net,proto3" json:"net,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginReq) GetInet() string {
	if m != nil {
		return m.Inet
	}
	return ""
}

func (m *LoginReq) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

func (m *LoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CmdExecReq struct {
	Dir                  string   `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args                 []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Timeout              int32    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdExecReq) Reset()         { *m = CmdExecReq{} }
func (m *CmdExecReq) String() string { return proto.CompactTextString(m) }
func (*CmdExecReq) ProtoMessage()    {}
func (*CmdExecReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{2}
}

func (m *CmdExecReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdExecReq.Unmarshal(m, b)
}
func (m *CmdExecReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdExecReq.Marshal(b, m, deterministic)
}
func (m *CmdExecReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdExecReq.Merge(m, src)
}
func (m *CmdExecReq) XXX_Size() int {
	return xxx_messageInfo_CmdExecReq.Size(m)
}
func (m *CmdExecReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdExecReq.DiscardUnknown(m)
}

var xxx_messageInfo_CmdExecReq proto.InternalMessageInfo

func (m *CmdExecReq) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *CmdExecReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CmdExecReq) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *CmdExecReq) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type CmdExecResp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	OutStr               string   `protobuf:"bytes,2,opt,name=outStr,proto3" json:"outStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdExecResp) Reset()         { *m = CmdExecResp{} }
func (m *CmdExecResp) String() string { return proto.CompactTextString(m) }
func (*CmdExecResp) ProtoMessage()    {}
func (*CmdExecResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{3}
}

func (m *CmdExecResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdExecResp.Unmarshal(m, b)
}
func (m *CmdExecResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdExecResp.Marshal(b, m, deterministic)
}
func (m *CmdExecResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdExecResp.Merge(m, src)
}
func (m *CmdExecResp) XXX_Size() int {
	return xxx_messageInfo_CmdExecResp.Size(m)
}
func (m *CmdExecResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdExecResp.DiscardUnknown(m)
}

var xxx_messageInfo_CmdExecResp proto.InternalMessageInfo

func (m *CmdExecResp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CmdExecResp) GetOutStr() string {
	if m != nil {
		return m.OutStr
	}
	return ""
}

type ProcessExecReq struct {
	Config               map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args                 []string          `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Dir                  string            `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty"`
	Id                   int32             `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string            `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProcessExecReq) Reset()         { *m = ProcessExecReq{} }
func (m *ProcessExecReq) String() string { return proto.CompactTextString(m) }
func (*ProcessExecReq) ProtoMessage()    {}
func (*ProcessExecReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{4}
}

func (m *ProcessExecReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessExecReq.Unmarshal(m, b)
}
func (m *ProcessExecReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessExecReq.Marshal(b, m, deterministic)
}
func (m *ProcessExecReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessExecReq.Merge(m, src)
}
func (m *ProcessExecReq) XXX_Size() int {
	return xxx_messageInfo_ProcessExecReq.Size(m)
}
func (m *ProcessExecReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessExecReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessExecReq proto.InternalMessageInfo

func (m *ProcessExecReq) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ProcessExecReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProcessExecReq) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ProcessExecReq) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *ProcessExecReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProcessExecReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ProcessExecResp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessExecResp) Reset()         { *m = ProcessExecResp{} }
func (m *ProcessExecResp) String() string { return proto.CompactTextString(m) }
func (*ProcessExecResp) ProtoMessage()    {}
func (*ProcessExecResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{5}
}

func (m *ProcessExecResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessExecResp.Unmarshal(m, b)
}
func (m *ProcessExecResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessExecResp.Marshal(b, m, deterministic)
}
func (m *ProcessExecResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessExecResp.Merge(m, src)
}
func (m *ProcessExecResp) XXX_Size() int {
	return xxx_messageInfo_ProcessExecResp.Size(m)
}
func (m *ProcessExecResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessExecResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessExecResp proto.InternalMessageInfo

func (m *ProcessExecResp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ProcessExecResp) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type ProcessSignalReq struct {
	Pid                  int32    `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Signal               int32    `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessSignalReq) Reset()         { *m = ProcessSignalReq{} }
func (m *ProcessSignalReq) String() string { return proto.CompactTextString(m) }
func (*ProcessSignalReq) ProtoMessage()    {}
func (*ProcessSignalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{6}
}

func (m *ProcessSignalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessSignalReq.Unmarshal(m, b)
}
func (m *ProcessSignalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessSignalReq.Marshal(b, m, deterministic)
}
func (m *ProcessSignalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessSignalReq.Merge(m, src)
}
func (m *ProcessSignalReq) XXX_Size() int {
	return xxx_messageInfo_ProcessSignalReq.Size(m)
}
func (m *ProcessSignalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessSignalReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessSignalReq proto.InternalMessageInfo

func (m *ProcessSignalReq) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ProcessSignalReq) GetSignal() int32 {
	if m != nil {
		return m.Signal
	}
	return 0
}

type ProcessSignalResp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessSignalResp) Reset()         { *m = ProcessSignalResp{} }
func (m *ProcessSignalResp) String() string { return proto.CompactTextString(m) }
func (*ProcessSignalResp) ProtoMessage()    {}
func (*ProcessSignalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{7}
}

func (m *ProcessSignalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessSignalResp.Unmarshal(m, b)
}
func (m *ProcessSignalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessSignalResp.Marshal(b, m, deterministic)
}
func (m *ProcessSignalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessSignalResp.Merge(m, src)
}
func (m *ProcessSignalResp) XXX_Size() int {
	return xxx_messageInfo_ProcessSignalResp.Size(m)
}
func (m *ProcessSignalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessSignalResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessSignalResp proto.InternalMessageInfo

func (m *ProcessSignalResp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ProcessStateReq struct {
	Ids                  []int32  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessStateReq) Reset()         { *m = ProcessStateReq{} }
func (m *ProcessStateReq) String() string { return proto.CompactTextString(m) }
func (*ProcessStateReq) ProtoMessage()    {}
func (*ProcessStateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{8}
}

func (m *ProcessStateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessStateReq.Unmarshal(m, b)
}
func (m *ProcessStateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessStateReq.Marshal(b, m, deterministic)
}
func (m *ProcessStateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessStateReq.Merge(m, src)
}
func (m *ProcessStateReq) XXX_Size() int {
	return xxx_messageInfo_ProcessStateReq.Size(m)
}
func (m *ProcessStateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessStateReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessStateReq proto.InternalMessageInfo

func (m *ProcessStateReq) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ProcessStateResp struct {
	States               map[int32]*ProcessState `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProcessStateResp) Reset()         { *m = ProcessStateResp{} }
func (m *ProcessStateResp) String() string { return proto.CompactTextString(m) }
func (*ProcessStateResp) ProtoMessage()    {}
func (*ProcessStateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{9}
}

func (m *ProcessStateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessStateResp.Unmarshal(m, b)
}
func (m *ProcessStateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessStateResp.Marshal(b, m, deterministic)
}
func (m *ProcessStateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessStateResp.Merge(m, src)
}
func (m *ProcessStateResp) XXX_Size() int {
	return xxx_messageInfo_ProcessStateResp.Size(m)
}
func (m *ProcessStateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessStateResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessStateResp proto.InternalMessageInfo

func (m *ProcessStateResp) GetStates() map[int32]*ProcessState {
	if m != nil {
		return m.States
	}
	return nil
}

type ProcessState struct {
	Pid                  int32    `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ExitMsg              string   `protobuf:"bytes,3,opt,name=exitMsg,proto3" json:"exitMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessState) Reset()         { *m = ProcessState{} }
func (m *ProcessState) String() string { return proto.CompactTextString(m) }
func (*ProcessState) ProtoMessage()    {}
func (*ProcessState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{10}
}

func (m *ProcessState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessState.Unmarshal(m, b)
}
func (m *ProcessState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessState.Marshal(b, m, deterministic)
}
func (m *ProcessState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessState.Merge(m, src)
}
func (m *ProcessState) XXX_Size() int {
	return xxx_messageInfo_ProcessState.Size(m)
}
func (m *ProcessState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessState.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessState proto.InternalMessageInfo

func (m *ProcessState) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ProcessState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ProcessState) GetExitMsg() string {
	if m != nil {
		return m.ExitMsg
	}
	return ""
}

type LogFileReq struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Payload              int32    `protobuf:"varint,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogFileReq) Reset()         { *m = LogFileReq{} }
func (m *LogFileReq) String() string { return proto.CompactTextString(m) }
func (*LogFileReq) ProtoMessage()    {}
func (*LogFileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{11}
}

func (m *LogFileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogFileReq.Unmarshal(m, b)
}
func (m *LogFileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogFileReq.Marshal(b, m, deterministic)
}
func (m *LogFileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogFileReq.Merge(m, src)
}
func (m *LogFileReq) XXX_Size() int {
	return xxx_messageInfo_LogFileReq.Size(m)
}
func (m *LogFileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogFileReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogFileReq proto.InternalMessageInfo

func (m *LogFileReq) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *LogFileReq) GetPayload() int32 {
	if m != nil {
		return m.Payload
	}
	return 0
}

type LogFileResp struct {
	Context              []byte   `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogFileResp) Reset()         { *m = LogFileResp{} }
func (m *LogFileResp) String() string { return proto.CompactTextString(m) }
func (*LogFileResp) ProtoMessage()    {}
func (*LogFileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{12}
}

func (m *LogFileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogFileResp.Unmarshal(m, b)
}
func (m *LogFileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogFileResp.Marshal(b, m, deterministic)
}
func (m *LogFileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogFileResp.Merge(m, src)
}
func (m *LogFileResp) XXX_Size() int {
	return xxx_messageInfo_LogFileResp.Size(m)
}
func (m *LogFileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogFileResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogFileResp proto.InternalMessageInfo

func (m *LogFileResp) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "loginReq")
	proto.RegisterType((*LoginResp)(nil), "loginResp")
	proto.RegisterType((*CmdExecReq)(nil), "cmdExecReq")
	proto.RegisterType((*CmdExecResp)(nil), "cmdExecResp")
	proto.RegisterType((*ProcessExecReq)(nil), "processExecReq")
	proto.RegisterMapType((map[string]string)(nil), "processExecReq.ConfigEntry")
	proto.RegisterType((*ProcessExecResp)(nil), "processExecResp")
	proto.RegisterType((*ProcessSignalReq)(nil), "processSignalReq")
	proto.RegisterType((*ProcessSignalResp)(nil), "processSignalResp")
	proto.RegisterType((*ProcessStateReq)(nil), "processStateReq")
	proto.RegisterType((*ProcessStateResp)(nil), "processStateResp")
	proto.RegisterMapType((map[int32]*ProcessState)(nil), "processStateResp.StatesEntry")
	proto.RegisterType((*ProcessState)(nil), "processState")
	proto.RegisterType((*LogFileReq)(nil), "logFileReq")
	proto.RegisterType((*LogFileResp)(nil), "logFileResp")
}

func init() { proto.RegisterFile("protobuf.proto", fileDescriptor_c77a803fcbc0c059) }

var fileDescriptor_c77a803fcbc0c059 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0xd8, 0xa4, 0xe3, 0x52, 0x82, 0x55, 0x21, 0x2b, 0x08, 0x11, 0x6d, 0x0f, 0xed,
	0xc9, 0x87, 0x56, 0x08, 0x8a, 0x38, 0x15, 0x15, 0x71, 0x41, 0x42, 0xce, 0xad, 0x27, 0x5c, 0x7b,
	0x63, 0xad, 0xe2, 0x78, 0x8d, 0x77, 0x83, 0x92, 0xdf, 0xc1, 0xdf, 0xe3, 0xc7, 0xa0, 0x19, 0xef,
	0xba, 0x76, 0xd5, 0x48, 0xbd, 0xbd, 0x37, 0xfb, 0x76, 0x3e, 0xde, 0x78, 0x0d, 0x27, 0x4d, 0x2b,
	0xb5, 0xbc, 0xdf, 0xae, 0x12, 0x02, 0xec, 0x0e, 0xa6, 0x95, 0x2c, 0x45, 0x9d, 0xf2, 0xdf, 0x51,
	0x04, 0x93, 0x3a, 0xdb, 0xf0, 0xd8, 0x59, 0x38, 0x17, 0x47, 0x29, 0x61, 0x8c, 0x89, 0x9a, 0xeb,
	0xd8, 0xed, 0x62, 0x88, 0xa3, 0x19, 0x78, 0x18, 0xf2, 0x28, 0x84, 0x30, 0x3a, 0x05, 0x5f, 0xcb,
	0x35, 0xaf, 0xe3, 0x09, 0xc5, 0x3a, 0xc2, 0xde, 0xc3, 0x91, 0xc9, 0xad, 0x1a, 0x4c, 0x94, 0xcb,
	0xa2, 0x4f, 0x8e, 0x98, 0xfd, 0x02, 0xc8, 0x37, 0xc5, 0xed, 0x8e, 0xe7, 0x58, 0x7e, 0x06, 0x5e,
	0x21, 0x5a, 0x23, 0x40, 0xd8, 0x37, 0xe4, 0x8e, 0x1b, 0xca, 0xda, 0x52, 0xc5, 0xde, 0xc2, 0xc3,
	0x18, 0xe2, 0x28, 0x86, 0x17, 0x5a, 0x6c, 0xb8, 0xdc, 0x6a, 0x6a, 0xc0, 0x4f, 0x2d, 0x65, 0xd7,
	0x10, 0xf6, 0x15, 0x9e, 0x6e, 0x22, 0x7a, 0x03, 0x81, 0xdc, 0xea, 0xa5, 0x6e, 0x4d, 0x19, 0xc3,
	0xd8, 0x3f, 0x87, 0xcc, 0xca, 0xb9, 0x52, 0xb6, 0xc3, 0x2b, 0x08, 0x72, 0x59, 0xaf, 0x44, 0x19,
	0x3b, 0x0b, 0xef, 0x22, 0xbc, 0x7c, 0x9b, 0x8c, 0x05, 0xc9, 0x57, 0x3a, 0xbd, 0xad, 0x75, 0xbb,
	0x4f, 0x8d, 0xf4, 0xd9, 0x43, 0x98, 0xf1, 0x27, 0x0f, 0xe3, 0x9f, 0x80, 0x2b, 0x8a, 0xd8, 0xa7,
	0x89, 0x5c, 0x51, 0xa0, 0x62, 0xcd, 0xf7, 0x71, 0xd0, 0x29, 0xd6, 0x7c, 0x3f, 0xbf, 0x86, 0x70,
	0x50, 0xd2, 0x0a, 0x9c, 0x5e, 0x80, 0x8b, 0xf9, 0x93, 0x55, 0x5b, 0x5b, 0xbd, 0x23, 0x9f, 0xdd,
	0x4f, 0x0e, 0xfb, 0x08, 0xaf, 0x46, 0xcd, 0x1f, 0x70, 0x67, 0x06, 0x5e, 0x23, 0x0a, 0xba, 0xee,
	0xa7, 0x08, 0xd9, 0x17, 0x98, 0x99, 0x8b, 0x4b, 0x51, 0xd6, 0x59, 0x65, 0x56, 0x87, 0x2a, 0xa7,
	0x57, 0xa1, 0xab, 0x8a, 0x8e, 0xcd, 0x55, 0xc3, 0xd8, 0x39, 0xbc, 0x7e, 0x74, 0xfb, 0xc0, 0xb7,
	0x71, 0xd6, 0xf7, 0xb7, 0xd4, 0x99, 0xe6, 0xa6, 0x8a, 0x28, 0x14, 0x79, 0xef, 0xa7, 0x08, 0xd9,
	0x5f, 0xe7, 0xa1, 0x99, 0x4e, 0xa5, 0x9a, 0xe8, 0x03, 0x04, 0x0a, 0x89, 0x32, 0x5b, 0x7a, 0x97,
	0x3c, 0x96, 0x24, 0x84, 0x94, 0xd9, 0x53, 0x27, 0x9e, 0x7f, 0x87, 0x70, 0x10, 0x1e, 0x7a, 0xe9,
	0x77, 0x5e, 0x9e, 0x0d, 0xbd, 0x0c, 0x2f, 0x5f, 0x8e, 0xd3, 0x0e, 0xac, 0xfd, 0x09, 0xc7, 0xc3,
	0xa3, 0x27, 0xdc, 0x39, 0x05, 0x9f, 0xaa, 0xda, 0xb5, 0x10, 0xc1, 0xcf, 0x98, 0xef, 0x84, 0xfe,
	0xa1, 0x4a, 0xf3, 0xb6, 0x2c, 0x65, 0x37, 0x00, 0x95, 0x2c, 0xbf, 0x89, 0x8a, 0x7c, 0x98, 0xc3,
	0x74, 0x25, 0x2a, 0x3e, 0x78, 0xab, 0x3d, 0xc7, 0x1c, 0x4d, 0xb6, 0xaf, 0x64, 0x66, 0x77, 0x66,
	0x29, 0x3b, 0x87, 0xb0, 0xcf, 0xa1, 0x1a, 0x14, 0xe6, 0xb2, 0xd6, 0x7c, 0xa7, 0x29, 0xc7, 0x71,
	0x6a, 0xe9, 0x0d, 0xdc, 0x4d, 0xe9, 0xdf, 0x90, 0xcb, 0xea, 0x3e, 0x20, 0x74, 0xf5, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0x90, 0xf0, 0xdf, 0x1a, 0x37, 0x04, 0x00, 0x00,
}
